number: '๐๑๒๓๔๕๖๗๘๙'
symbol: '๐๑๒๓๔๕๖๗๘๙'
lang_char: '๐๑๒๓๔๕๖๗๘๙'
experiment_name: 'th_filtered'
train_data: 'all_data'
valid_data: 'all_data/th_val'
manualSeed: 1111
workers: 6
batch_size: 32 #32
num_iter: 100
valInterval: 50
saved_model: '' #'saved_models/en_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'th_train_filtered' # this is dataset folder in train_data
batch_ratio: '1.0' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: 0.0
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False